// DO NOT EDIT THIS FILE BY HAND, IT IS GENERATED BY RETRIEVEHTML.TS

import { HasIdAndElementCoords } from "../../../src/types";
export const irregulargrid: HasIdAndElementCoords[] = [
  {
    "id": "A",
    "top": 10,
    "left": 10,
    "right": 214,
    "bottom": 214,
    "width": 204,
    "height": 204,
    "x": 10,
    "y": 10
  },
  {
    "id": "B",
    "top": 210,
    "left": 314,
    "right": 618,
    "bottom": 304,
    "width": 304,
    "height": 94,
    "x": 314,
    "y": 210
  },
  {
    "id": "C",
    "top": 370,
    "left": 718,
    "right": 822,
    "bottom": 424,
    "width": 104,
    "height": 54,
    "x": 718,
    "y": 370
  },
  {
    "id": "D",
    "top": 570,
    "left": 872,
    "right": 976,
    "bottom": 634,
    "width": 104,
    "height": 64,
    "x": 872,
    "y": 570
  },
  {
    "id": "E",
    "top": 210,
    "left": 1026,
    "right": 1130,
    "bottom": 274,
    "width": 104,
    "height": 64,
    "x": 1026,
    "y": 210
  }
]