// DO NOT EDIT THIS FILE BY HAND, IT IS GENERATED BY RETRIEVEHTML.TS

import { IsHtmlElementLike } from "../../../src/types";
export const irregulargrid: IsHtmlElementLike[] = [{
 id: "A",
getBoundingClientRect: () => ({
          top: 10,
          left: 10,
          right: 214,
          bottom: 214,
          height: 204,
          width: 204,
          x: 10,
          y: 10 
})
},{
 id: "B",
getBoundingClientRect: () => ({
          top: 210,
          left: 314,
          right: 618,
          bottom: 304,
          height: 94,
          width: 304,
          x: 314,
          y: 210 
})
},{
 id: "C",
getBoundingClientRect: () => ({
          top: 370,
          left: 718,
          right: 822,
          bottom: 424,
          height: 54,
          width: 104,
          x: 718,
          y: 370 
})
},{
 id: "D",
getBoundingClientRect: () => ({
          top: 570,
          left: 872,
          right: 976,
          bottom: 634,
          height: 64,
          width: 104,
          x: 872,
          y: 570 
})
},{
 id: "E",
getBoundingClientRect: () => ({
          top: 210,
          left: 1026,
          right: 1130,
          bottom: 274,
          height: 64,
          width: 104,
          x: 1026,
          y: 210 
})
}]
