// DO NOT EDIT THIS FILE BY HAND, IT IS GENERATED BY RETRIEVEHTML.TS

import { HasIdAndElementCoords } from "../../../src/types";
export const irregulargrid: HasIdAndElementCoords[] = [
  {
    "id": "A",
    "top": 10,
    "left": 10,
    "right": 64.01666259765625,
    "bottom": 630,
    "width": 54.01666259765625,
    "height": 620,
    "x": 10,
    "y": 10
  },
  {
    "id": "B",
    "top": 210,
    "left": 164.01666259765625,
    "right": 464.01666259765625,
    "bottom": 300,
    "width": 300,
    "height": 90,
    "x": 164.01666259765625,
    "y": 210
  },
  {
    "id": "C",
    "top": 370,
    "left": 564.0166625976562,
    "right": 664.0166625976562,
    "bottom": 420,
    "width": 100,
    "height": 50,
    "x": 564.0166625976562,
    "y": 370
  },
  {
    "id": "D",
    "top": 570,
    "left": 714.0166625976562,
    "right": 814.0166625976562,
    "bottom": 630,
    "width": 100,
    "height": 60,
    "x": 714.0166625976562,
    "y": 570
  }
]