// DO NOT EDIT THIS FILE BY HAND, IT IS GENERATED BY RETRIEVEHTML.TS

import { IsHtmlElementLike } from "../../../src/types";
export const overlappinggrid: IsHtmlElementLike[] = [{
 id: "C",
getBoundingClientRect: () => ({
          top: 135,
          left: 10,
          right: 214,
          bottom: 339,
          height: 204,
          width: 204,
          x: 10,
          y: 135 
})
},{
 id: "B",
getBoundingClientRect: () => ({
          top: 170,
          left: 10,
          right: 314,
          bottom: 264,
          height: 94,
          width: 304,
          x: 10,
          y: 170 
})
},{
 id: "A",
getBoundingClientRect: () => ({
          top: 20,
          left: 10,
          right: 314,
          bottom: 114,
          height: 94,
          width: 304,
          x: 10,
          y: 20 
})
},{
 id: "D",
getBoundingClientRect: () => ({
          top: 170,
          left: 275,
          right: 579,
          bottom: 264,
          height: 94,
          width: 304,
          x: 275,
          y: 170 
})
}]