// DO NOT EDIT THIS FILE BY HAND, IT IS GENERATED BY RETRIEVEHTML.TS

import { HasIdAndElementCoords } from "../../../src/types";
export const simplegrid: HasIdAndElementCoords[] = [
  {
    "id": "A",
    "top": 10,
    "left": 10,
    "right": 214,
    "bottom": 214,
    "width": 204,
    "height": 204,
    "x": 10,
    "y": 10
  },
  {
    "id": "B",
    "top": 10,
    "left": 214,
    "right": 418,
    "bottom": 214,
    "width": 204,
    "height": 204,
    "x": 214,
    "y": 10
  },
  {
    "id": "C",
    "top": 10,
    "left": 418,
    "right": 622,
    "bottom": 214,
    "width": 204,
    "height": 204,
    "x": 418,
    "y": 10
  },
  {
    "id": "D",
    "top": 214,
    "left": 10,
    "right": 214,
    "bottom": 418,
    "width": 204,
    "height": 204,
    "x": 10,
    "y": 214
  },
  {
    "id": "E",
    "top": 214,
    "left": 214,
    "right": 418,
    "bottom": 418,
    "width": 204,
    "height": 204,
    "x": 214,
    "y": 214
  },
  {
    "id": "F",
    "top": 214,
    "left": 418,
    "right": 622,
    "bottom": 418,
    "width": 204,
    "height": 204,
    "x": 418,
    "y": 214
  },
  {
    "id": "G",
    "top": 418,
    "left": 10,
    "right": 214,
    "bottom": 622,
    "width": 204,
    "height": 204,
    "x": 10,
    "y": 418
  },
  {
    "id": "H",
    "top": 418,
    "left": 214,
    "right": 418,
    "bottom": 622,
    "width": 204,
    "height": 204,
    "x": 214,
    "y": 418
  },
  {
    "id": "I",
    "top": 418,
    "left": 418,
    "right": 622,
    "bottom": 622,
    "width": 204,
    "height": 204,
    "x": 418,
    "y": 418
  },
  {
    "id": "J",
    "top": 622,
    "left": 10,
    "right": 214,
    "bottom": 826,
    "width": 204,
    "height": 204,
    "x": 10,
    "y": 622
  },
  {
    "id": "K",
    "top": 622,
    "left": 214,
    "right": 418,
    "bottom": 826,
    "width": 204,
    "height": 204,
    "x": 214,
    "y": 622
  },
  {
    "id": "L",
    "top": 622,
    "left": 418,
    "right": 622,
    "bottom": 826,
    "width": 204,
    "height": 204,
    "x": 418,
    "y": 622
  },
  {
    "id": "N",
    "top": 826,
    "left": 10,
    "right": 214,
    "bottom": 1030,
    "width": 204,
    "height": 204,
    "x": 10,
    "y": 826
  },
  {
    "id": "M",
    "top": 826,
    "left": 214,
    "right": 418,
    "bottom": 1030,
    "width": 204,
    "height": 204,
    "x": 214,
    "y": 826
  },
  {
    "id": "O",
    "top": 826,
    "left": 418,
    "right": 622,
    "bottom": 1030,
    "width": 204,
    "height": 204,
    "x": 418,
    "y": 826
  },
  {
    "id": "P",
    "top": 1030,
    "left": 10,
    "right": 214,
    "bottom": 1234,
    "width": 204,
    "height": 204,
    "x": 10,
    "y": 1030
  },
  {
    "id": "Q",
    "top": 1030,
    "left": 214,
    "right": 418,
    "bottom": 1234,
    "width": 204,
    "height": 204,
    "x": 214,
    "y": 1030
  },
  {
    "id": "R",
    "top": 1030,
    "left": 418,
    "right": 622,
    "bottom": 1234,
    "width": 204,
    "height": 204,
    "x": 418,
    "y": 1030
  },
  {
    "id": "S",
    "top": 1234,
    "left": 10,
    "right": 214,
    "bottom": 1438,
    "width": 204,
    "height": 204,
    "x": 10,
    "y": 1234
  },
  {
    "id": "T",
    "top": 1234,
    "left": 214,
    "right": 418,
    "bottom": 1438,
    "width": 204,
    "height": 204,
    "x": 214,
    "y": 1234
  }
]