// DO NOT EDIT THIS FILE BY HAND, IT IS GENERATED BY RETRIEVEHTML.TS

import { IsHtmlElementLike } from "../../../src/types";
export const simplegrid: IsHtmlElementLike[] = [{
  id: "A",
  getBoundingClientRect: () => ({
    top: 10,
    left: 10,
    right: 214,
    bottom: 214,
    height: 204,
    width: 204,
    x: 10,
    y: 10
  })
}, {
  id: "B",
  getBoundingClientRect: () => ({
    top: 10,
    left: 214,
    right: 418,
    bottom: 214,
    height: 204,
    width: 204,
    x: 214,
    y: 10
  })
}, {
  id: "C",
  getBoundingClientRect: () => ({
    top: 10,
    left: 418,
    right: 622,
    bottom: 214,
    height: 204,
    width: 204,
    x: 418,
    y: 10
  })
}, {
  id: "D",
  getBoundingClientRect: () => ({
    top: 214,
    left: 10,
    right: 214,
    bottom: 418,
    height: 204,
    width: 204,
    x: 10,
    y: 214
  })
}, {
  id: "E",
  getBoundingClientRect: () => ({
    top: 214,
    left: 214,
    right: 418,
    bottom: 418,
    height: 204,
    width: 204,
    x: 214,
    y: 214
  })
}, {
  id: "F",
  getBoundingClientRect: () => ({
    top: 214,
    left: 418,
    right: 622,
    bottom: 418,
    height: 204,
    width: 204,
    x: 418,
    y: 214
  })
}, {
  id: "G",
  getBoundingClientRect: () => ({
    top: 418,
    left: 10,
    right: 214,
    bottom: 622,
    height: 204,
    width: 204,
    x: 10,
    y: 418
  })
}, {
  id: "H",
  getBoundingClientRect: () => ({
    top: 418,
    left: 214,
    right: 418,
    bottom: 622,
    height: 204,
    width: 204,
    x: 214,
    y: 418
  })
}, {
  id: "I",
  getBoundingClientRect: () => ({
    top: 418,
    left: 418,
    right: 622,
    bottom: 622,
    height: 204,
    width: 204,
    x: 418,
    y: 418
  })
}, {
  id: "J",
  getBoundingClientRect: () => ({
    top: 622,
    left: 10,
    right: 214,
    bottom: 826,
    height: 204,
    width: 204,
    x: 10,
    y: 622
  })
}, {
  id: "K",
  getBoundingClientRect: () => ({
    top: 622,
    left: 214,
    right: 418,
    bottom: 826,
    height: 204,
    width: 204,
    x: 214,
    y: 622
  })
}, {
  id: "L",
  getBoundingClientRect: () => ({
    top: 622,
    left: 418,
    right: 622,
    bottom: 826,
    height: 204,
    width: 204,
    x: 418,
    y: 622
  })
}, {
  id: "N",
  getBoundingClientRect: () => ({
    top: 826,
    left: 10,
    right: 214,
    bottom: 1030,
    height: 204,
    width: 204,
    x: 10,
    y: 826
  })
}, {
  id: "M",
  getBoundingClientRect: () => ({
    top: 826,
    left: 214,
    right: 418,
    bottom: 1030,
    height: 204,
    width: 204,
    x: 214,
    y: 826
  })
}, {
  id: "O",
  getBoundingClientRect: () => ({
    top: 826,
    left: 418,
    right: 622,
    bottom: 1030,
    height: 204,
    width: 204,
    x: 418,
    y: 826
  })
}, {
  id: "P",
  getBoundingClientRect: () => ({
    top: 1030,
    left: 10,
    right: 214,
    bottom: 1234,
    height: 204,
    width: 204,
    x: 10,
    y: 1030
  })
}, {
  id: "Q",
  getBoundingClientRect: () => ({
    top: 1030,
    left: 214,
    right: 418,
    bottom: 1234,
    height: 204,
    width: 204,
    x: 214,
    y: 1030
  })
}, {
  id: "R",
  getBoundingClientRect: () => ({
    top: 1030,
    left: 418,
    right: 622,
    bottom: 1234,
    height: 204,
    width: 204,
    x: 418,
    y: 1030
  })
}, {
  id: "S",
  getBoundingClientRect: () => ({
    top: 1234,
    left: 10,
    right: 214,
    bottom: 1438,
    height: 204,
    width: 204,
    x: 10,
    y: 1234
  })
}, {
  id: "T",
  getBoundingClientRect: () => ({
    top: 1234,
    left: 214,
    right: 418,
    bottom: 1438,
    height: 204,
    width: 204,
    x: 214,
    y: 1234
  })
}]
