// DO NOT EDIT THIS FILE BY HAND, IT IS GENERATED BY RETRIEVEHTML.TS

import { HasIdAndElementCoords } from "../../../src/types";
export const varyingsizes: HasIdAndElementCoords[] = [
  {
    "id": "A",
    "top": 60,
    "left": 10,
    "right": 89,
    "bottom": 139,
    "width": 79,
    "height": 79,
    "x": 10,
    "y": 60
  },
  {
    "id": "B",
    "top": 10,
    "left": 89,
    "right": 133,
    "bottom": 314,
    "width": 44,
    "height": 304,
    "x": 89,
    "y": 10
  },
  {
    "id": "C",
    "top": 30,
    "left": 133,
    "right": 177,
    "bottom": 84,
    "width": 44,
    "height": 54,
    "x": 133,
    "y": 30
  },
  {
    "id": "D",
    "top": 110,
    "left": 177,
    "right": 221,
    "bottom": 164,
    "width": 44,
    "height": 54,
    "x": 177,
    "y": 110
  },
  {
    "id": "E",
    "top": 314,
    "left": 310,
    "right": 410,
    "bottom": 343,
    "width": 100,
    "height": 29,
    "x": 310,
    "y": 314
  },
  {
    "id": "F",
    "top": 343,
    "left": 10,
    "right": 514,
    "bottom": 372,
    "width": 504,
    "height": 29,
    "x": 10,
    "y": 343
  },
  {
    "id": "G",
    "top": 372,
    "left": 10,
    "right": 514,
    "bottom": 426,
    "width": 504,
    "height": 54,
    "x": 10,
    "y": 372
  }
]